### PR TITLE
Remove bench regression workflow

### PR DESCRIPTION
**Pull request by ntampakas**
Benchmarks workflow fails due to an unrecognized option.
This PR resolves this issue, by removing the unknown flag.

Issue URL: #39

### CODE REVIEW

**Comment by CPerezz** [comment]
Have we checked that it successfully prints out the bench results in a comment?? (this was the initial purpose of the creation of this command).

@ntampakas

**Comment by ntampakas** [comment]
@CPerezz,

I ran the bench on a forked repo and the following message popped up:
```
    Finished bench [optimized] target(s) in 3m 08s
     Running unittests (target/release/deps/halo2-47e61900814371ad)

     Running unittests (target/release/deps/arithmetic-bc1f2b742b864289)
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend
     Running unittests (target/release/deps/plonk-0202f881d7a0afa1)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend

```

It seems no test is being executed, so no benchmark result can be found.

**Comment by CPerezz** [comment]
We should use `make bench` instead of cargo bench as we don't do benches niçormally but rather inside of tests due to long runs.

See the project benchmark to view the precise command.

Aside from that, also important to note that we should do something like `&> output.txt` and then use it's contents to write the PR comment.

**Comment by ntampakas** [comment]
> We should use `make bench` instead of cargo bench as we don't do benches niçormally but rather inside of tests due to long runs.
> 
> See the project benchmark to view the precise command.

I checked the github-action-benchmark project and it is mentioned the **cargo +nightly bench** command for cargo test execution.
Or i' m missing something?
 
> Aside from that, also important to note that we should do something like `&> output.txt` and then use it's contents to write the PR comment.

**tee** also does this work (copying standard input to output.txt file)

I' m performing some benches against local instances, as well as GH virtual machines.
Benchmark executions seems to work fine, but the pipeline fails on that point where github-action-benchmark searching for valid benchmark results in the output.txt file.
I' m digging around and as far as i can see, github-action-benchmark does not support criterion results (not 100% sure).

**Comment by ed255** [comment]
It seems this github action runs a benchmark already defined in the upstream halo2, not a the benchmark we defined ourselves with our own circuits. See https://github.com/zcash/halo2/blob/main/.github/workflows/bench.yml for reference.
I also noticed that we're not specifying the rust version, so maybe the version that the github action is using doesn't have that flag?  It'd be better to specify an explicit rust version.

**Comment by ntampakas** [comment]
I found out this comment mentioned here: https://github.com/zcash/halo2/commit/55364f0d998b5752b9edfbafb5847b8d3306e3fb:

[snip]
_In order to pass criterion flags via `cargo bench`, we need to ensure
that all benchmarks use it (otherwise the flags are rejected by the
built-in benchmark harness as unknown). Since we don't actually have any
benchmarks inside the library itself, we simply disable its benchmark
harness._
[snap]

@CPerezz @ed255 yous comments please.

**Comment by ed255** [comment]
Upon further inspection, I see that this same issue is happening upstream.  I tested it locally, and I also saw it in their github action results: https://github.com/zcash/halo2/runs/5849884040?check_suite_focus=true#step:4:269

AFAIK we have our own benchmark procedure using our own circuits, so my suggestion would be to ignore / disable this github action.

**Review by ed255 — APPROVED** [review]
LGTM!

**Review by CPerezz — APPROVED** [review]
LGTM!

Will we work anyway on the reporting tool? SO that when a benchmark is executed we get reports in the PR discussion?

**Comment by AronisAt79** [comment]
> LGTM!
> 
> Will we work anyway on the reporting tool? SO that when a benchmark is executed we get reports in the PR discussion?

@CPerezz , yes this is one of the workflow enhancements we have in our backlog :)

**Pull request merged**
