### PR TITLE
use Rotation to do KZG's multiopen 

### PR DESCRIPTION
**Pull request by TrapdoorHeader**
## Motivation

In order to implement an `external circuit` that verifies an `internal circuit`, we need to fix the order of these opening points `{ x*w^i }`. The current implemented KZG multiopen scheme order them by their numeric value. However, note that different `x` will cause the order of this set change dramatically. 

## Approach 
We propose to order this set by the rotation, i.e. `i`. 

Signed-off-by: TrapdoorHeader <support@trapdoortech.com>

### CODE REVIEW

**Comment by barryWhiteHat** [comment]
I think we already merged https://github.com/zcash/halo2/pull/408 so our halo2 lib should already support multi open with rotation. Can you confirm ?

**Comment by barryWhiteHat** [comment]
Never mind. Seems we odn't include that

**Comment by ChihChengLiang** [comment]
@kilic What branch should this PR merge to?

**Comment by kilic** [comment]
Closing due to #27

**Pull request closed without merging**
