### PR TITLE
`lookup_any`

### PR DESCRIPTION
**Pull request by NoCtrlZ**

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Looks like this PR depends on lots of commits in #3, is it possible to isolate just the lookup2 part without the commits from #3?

**Comment by NoCtrlZ** [comment]
Hi @ChihChengLiang 
I think it's impossible because this commit depends on kilic branch.
You can check diff with following 👍
https://github.com/kilic/halo2/pull/2

**Comment by kilic** [comment]
Looks good to me. Upstream pairing repo is also updated with `get_lower_128` method.

**Comment by CPerezz** [comment]
This needs to resolve the conflicts/be rebased into `main` and then merged. 

On that way https://github.com/appliedzkp/zkevm-circuits/pull/199 becomes unblocked.

**Comment by NoCtrlZ** [comment]
I am going to fix clippy

**Review by CPerezz — APPROVED** [review]
LGTM

**Comment by kilic** [comment]
Looks good to me

**Review by kilic — APPROVED** [review]
Looks good to me

**Pull request merged**
